function schema = pitch_log_schema()
%PITCH_LOG_SCHEMA Canonical CSV contract for future pitch identification.

name = [ ...
    "sample_index"; "time_us"; "experiment_phase"; ...
    "raw_ref_rad"; "planned_ref_rad"; "imu_angle_rad"; ...
    "gyro_x_rad_s"; "gyro_y_rad_s"; "gyro_z_rad_s"; ...
    "motor_angle_rad"; "motor_velocity_rad_s"; ...
    "torque_command_nm"; "torque_feedback_nm"; ...
    "motor_mos_temp_c"; "motor_coil_temp_c"];
unit = [ ...
    "count"; "us"; "category"; ...
    "rad"; "rad"; "rad"; ...
    "rad/s"; "rad/s"; "rad/s"; ...
    "rad"; "rad/s"; "Nm"; "Nm"; "degC"; "degC"];
required = [ ...
    true; true; true; true; true; true; true; true; true; ...
    true; true; true; true; false; false];
description = [ ...
    "Monotonic target-side sample counter"; ...
    "Target timestamp captured in the control tick"; ...
    "stationary/linkage_sweep/static_hold/constant_velocity/dynamic"; ...
    "Unshaped command-layer reference"; ...
    "Trajectory-generator output"; ...
    "INS pitch angle"; ...
    "Raw calibrated body gyro X"; ...
    "Raw calibrated body gyro Y"; ...
    "Raw calibrated body gyro Z"; ...
    "DM motor position"; ...
    "DM motor velocity"; ...
    "Total commanded motor torque"; ...
    "DM reported motor torque"; ...
    "MOS temperature"; ...
    "Coil temperature"];
schema = table(name, unit, required, description);
end

