function checks = pitch_self_test(cfg, linear, designs)
%PITCH_SELF_TEST Structural and numerical checks for the offline package.

checks = struct();
checks.provisional_flag = cfg.meta.provisional;
checks.controllable = linear.controllability_rank == 2;
checks.observable = linear.observability_rank == 2;
checks.lqi_stable = all(abs(designs.lqi.poles) < 1.0);

angle_estimator = (eye(3) - designs.eso.L_angle * designs.eso.C_angle) * ...
    designs.eso.Ad;
dual_estimator = (eye(3) - designs.eso.L_dual * designs.eso.C_dual) * ...
    designs.eso.Ad;
checks.eso_angle_stable = all(abs(eig(angle_estimator)) < 1.0);
checks.eso_dual_stable = all(abs(eig(dual_estimator)) < 1.0);

theta_test = [-0.30, 0.0, 0.30];
equilibrium_error = zeros(size(theta_test));
for idx = 1:numel(theta_test)
    terms = pitch_model_terms(theta_test(idx), 0.0, cfg.model);
    tau_motor = terms.gravity_generalized_nm / terms.ratio;
    equilibrium_error(idx) = terms.ratio * tau_motor - ...
        terms.gravity_generalized_nm;
end
checks.max_equilibrium_error_nm = max(abs(equilibrium_error));
checks.equilibrium_balanced = checks.max_equilibrium_error_nm < 1.0e-9;

scenarios = pitch_make_scenarios(cfg);
ideal = scenarios(strcmp({scenarios.name}, 'ideal_step_up'));
% The strict ideal tracking requirement is applied to the nominal LQI
% baseline. ESO is validated separately below because its transient estimate
% intentionally trades a small amount of overshoot for disturbance rejection.
ideal_result = pitch_simulate(cfg, designs, ideal, 'lqi', cfg.random_seed);
checks.ideal_finite = all(isfinite(ideal_result.trace.theta_rad)) && ...
    all(isfinite(ideal_result.trace.tau_cmd_nm));
checks.ideal_stable = ideal_result.metrics.stable;
checks.ideal_meets_tracking = ideal_result.metrics.settling_time_s <= ...
    cfg.design.target_settle_s && ...
    ideal_result.metrics.overshoot_rad <= cfg.design.target_overshoot_rad && ...
    ideal_result.metrics.steady_error_rad <= cfg.design.target_steady_error_rad;
checks.integral_bounded = ideal_result.metrics.max_integral_rad_s <= ...
    cfg.limits.integral_rad_s + 1.0e-9;
checks.ideal_metrics = ideal_result.metrics;

ideal_eso_result = pitch_simulate(cfg, designs, ideal, 'lqi_eso', ...
    cfg.random_seed + 1);
checks.ideal_eso_stable = ideal_eso_result.metrics.stable && ...
    all(isfinite(ideal_eso_result.trace.theta_rad)) && ...
    all(isfinite(ideal_eso_result.trace.eso_disturbance_rad_s2));
checks.ideal_eso_metrics = ideal_eso_result.metrics;

disturbance = scenarios(strcmp({scenarios.name}, 'disturbance_pulse'));
angle_only_designs = designs;
angle_only_designs.eso.use_dual_measurement = false;
angle_only_result = pitch_simulate(cfg, angle_only_designs, disturbance, ...
    'lqi_eso', cfg.random_seed + 77);
angle_only_finite = all(isfinite(angle_only_result.trace.eso_theta_rad)) && ...
    all(isfinite(angle_only_result.trace.eso_omega_rad_s)) && ...
    all(isfinite(angle_only_result.trace.eso_disturbance_rad_s2));
checks.eso_angle_dynamic_stable = angle_only_result.metrics.stable && ...
    angle_only_finite;
checks.eso_angle_theta_rms_error_rad = sqrt(mean((...
    angle_only_result.trace.eso_theta_rad - ...
    angle_only_result.trace.theta_rad).^2));
checks.eso_angle_omega_rms_error_rad_s = sqrt(mean((...
    angle_only_result.trace.eso_omega_rad_s - ...
    angle_only_result.trace.omega_rad_s).^2));

large_step = scenarios(strcmp({scenarios.name}, 'step_up_center'));
large_step.name = 'antiwindup_recovery';
large_step.amplitude_rad = deg2rad(10.0);
large_step.duration_s = 1.5;
large_step_result = pitch_simulate(cfg, designs, large_step, 'lqi_eso', ...
    cfg.random_seed + 91);
checks.saturation_exercised = any(large_step_result.trace.saturated > 0.5);
checks.saturation_recovered = large_step_result.metrics.stable && ...
    large_step_result.metrics.max_integral_rad_s <= ...
        cfg.limits.integral_rad_s + 1.0e-9 && ...
    large_step_result.metrics.steady_error_rad <= deg2rad(0.15);
checks.saturation_recovery_metrics = large_step_result.metrics;

sample_count = 250;
sample_index = (1:sample_count)';
time_us = 1000.0 * (0:sample_count-1)';
experiment_phase = repmat("stationary", sample_count, 1);
zeros_column = zeros(sample_count, 1);
synthetic_log = table(sample_index, time_us, experiment_phase, ...
    zeros_column, zeros_column, zeros_column, zeros_column, zeros_column, ...
    zeros_column, zeros_column, zeros_column, zeros_column, zeros_column, ...
    'VariableNames', {'sample_index', 'time_us', 'experiment_phase', ...
    'raw_ref_rad', 'planned_ref_rad', 'imu_angle_rad', 'gyro_x_rad_s', ...
    'gyro_y_rad_s', 'gyro_z_rad_s', 'motor_angle_rad', ...
    'motor_velocity_rad_s', 'torque_command_nm', 'torque_feedback_nm'});
synthetic_id = pitch_identify_from_log(synthetic_log, cfg);
checks.identification_interface = synthetic_id.meta.provisional && ...
    synthetic_id.noise.available && ~synthetic_id.meta.validated;

required = {'provisional_flag', 'controllable', 'observable', 'lqi_stable', ...
    'eso_angle_stable', 'eso_dual_stable', 'equilibrium_balanced', ...
    'ideal_finite', 'ideal_stable', 'ideal_meets_tracking', ...
    'ideal_eso_stable', ...
    'integral_bounded', 'eso_angle_dynamic_stable', ...
    'saturation_exercised', 'saturation_recovered', ...
    'identification_interface'};
for idx = 1:numel(required)
    if ~checks.(required{idx})
        error('pitch:selftest:Failed', 'Self-test failed: %s', required{idx});
    end
end
end
